Repository jenkins-x/jenkins-x-platform, pull requests merged in 2018-10, with the labels that each got.

#4180 feat: attempting to update org repos as downstream build
  .updatebot.yml
  Makefile
Labels: approved, size/XS

#4185 Revert "update jenkinsxio/builder-base to 0.1.12"
  values.yaml
Labels: approved, size/S

#4186 feat: Add compliancecontroller
  requirements.yaml
  values.yaml
Labels: approved, size/M

#4190 fix: fix role for compliance controller
  values.yaml
Labels: approved, size/S

#4191 fix: more roles for compliance controller!
  values.yaml
Labels: approved, size/XS

#4184 Added Maven-Java11 builder
  values.yaml
Labels: approved, size/M

#4183 Add a Newman pod template
  values.yaml
Labels: approved, size/M

#4196 Fix for cronjobs gcpreviews and gcactivities not being created
  requirements.yaml
Labels: approved, size/XS

#4201 Fix: more renaming to commitstatus
  requirements.yaml
Labels: approved, size/S

#4204 feat: update jenkinsx image to 0.0.34 which contains Jenkins version 2.143
  values.yaml
Labels: approved, size/XS

#4224 fix: update jnlp-slave to version 3.26-1
  values.yaml
Labels: approved, size/M

#4227 chore: update resource name
  values.yaml
Labels: approved, size/XS

#4228 base64 encoding is already handled
  templates/docker-cfg-secret.yaml
  templates/jenkins-x-github-secret.yaml
Labels: approved, lgtm, size/XS

#4237 feat: enable the extensions repo by default
  templates/jenkins-x-extensions-config.yaml
  values.yaml
Labels: approved, size/S
