Repository jenkins-x/jenkins-x-platform, pull requests merged in 2018-11, with the labels that each got.

#4244 chore: improve devpod ports
  values.yaml
Labels: approved, size/XS

#4242 fix: add configmap to roles for commit status controller
  values.yaml
Labels: approved, size/XS

#4245 fix: downgrade theia to working version
  templates/jenkins-x-devpod-config.yaml
Labels: approved, size/XS

#4248 fix: role controller roles
  templates/docker-cfg-secret.yaml
  values.yaml
Labels: approved, size/M

#4255 fix: upgrade exposecontroller
  requirements.yaml
Labels: approved, size/XS

#4267 fix: updating makefile to use the correct chartmuseum endpoints
  Makefile
Labels: approved, size/XS

#4271 fix: try to use the correct chart repo
  Makefile
  requirements.yaml
Labels: approved, size/S

#4278 fix: add role for controllercommitstatus
  values.yaml
Labels: approved, size/XS

#4277 fix: update all jx releases to use http://chartmuseum.jenkins-x.io
  Makefile
  jx/scripts/release.sh
  requirements.yaml
Labels: approved, size/S

#4287 feat(jx-infra) added gcs-jenkinsx-chartmuseum secret config
  templates/gcs-jenkinsx-chartmuseum-secret.yaml
Labels: approved, size/XS

#4295 fix missing base64 encoding
  templates/docker-cfg-secret.yaml
  templates/jenkins-x-github-secret.yaml
Labels: approved, size/XS

#4303 allow jenkins installation to be configurable, when using serverless it is not needed to run all the time
  requirements.yaml
  values.yaml
Labels: approved, size/XS

#4316 fix: gcpods job
  requirements.yaml
Labels: approved, size/XS

#4331 feat: add support for an optional post install job
  requirements.yaml
  values.yaml
Labels: approved, size/M

#4330 Give users permissions for other api groups than core and jenkins.io
  templates/committer-role.yaml
  templates/owner-role.yaml
  templates/viewer-role.yaml
Labels: approved, size/M
