Repository jenkins-x/jenkins-x-platform, pull requests merged in 2018-12, with the labels that each got.

#4340 Allow to configure tolerations for builder pods
  templates/jenkins-x-pod-templates.yaml
  values.yaml
Labels: approved, lgtm, size/L

#4404 Revert "the team controller was stuck on a very old version of jx."
  values.yaml
Labels: lgtm, size/XS

#4424 fix: add build controller for knative
  Makefile
  requirements.yaml
  values.yaml
Labels: approved, size/M

#4435 fix: build controller's git configuration
  values.yaml
Labels: approved, size/XS

#4441 fix: lets use a docker image for build controller that has git
  values.yaml
Labels: approved, size/XS

#4439 Adding Python 3.7 builder pod template
  values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#4502 refactor(secrets): cleanup the unused git secrets
  templates/docker-cfg-secret.yaml
  templates/git-credentials-secret.yaml
  templates/github-api-token-secret.yaml
  templates/jenkins-git-ssh-secret.yaml
  templates/jenkins-x-github-secret.yaml
  templates/release-gpg-secret.yaml
  values.yaml
Labels: approved, lgtm, size/M

#4515 add a Jenkins X specific view role
  templates/jx-view-role.yaml
Labels: approved, size/S

#4516 refactor(secrets): remove the old GitHub enterprise secret 'ghe-test-user'
  templates/jenkins-x-ghe-test-user.yaml
Labels: approved, size/S

#4514 Added in annotation option in cm for pod templates
  templates/jenkins-x-pod-templates.yaml
  values.yaml
Labels: approved, ok-to-test, size/S

#4522 fix: update roles on the gc jobs
  values.yaml
Labels: approved, size/S

#4530 fix: lets enable batch mode for the jobs
  values.yaml
Labels: approved, size/XS
