Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-07, with the labels that each got.

#5616 create Packer pod template
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#5664 chore: make running exposecontroller optional
  jenkins-x-platform/requirements.yaml
  jenkins-x-platform/values.yaml
Labels: approved, size/XS

#5706 chore: switch to new updatebot and add release notes
  .updatebot.yml
  Makefile
Labels: approved, size/XS

#5719 fix: readd .updatebot.yml for now
  .updatebot.yml
Labels: approved, lgtm, size/XS

#5723 fix: standardise build images
  jenkins-x-platform/values.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/M

#5727 chore: tidy owners
  OWNERS
Labels: approved, size/XS

#5728 fix: jx step create pr regex --regex, not jx step create pr --regex
  Makefile
Labels: approved, lgtm, size/XS

#5731 fix: jx step create pr versions, not jx step create version pr
  Makefile
Labels: approved, size/XS

#5744 chore(deps): bump jenkins-x/jenkins-x-builders from 0.1.560 to 0.1.564
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  jenkins-x-platform/values.yaml
Labels: size/M, updatebot

#5746 fix: Use latest builder versions in pipeline to hopefully fix release
  jenkins-x.yml
Labels: approved, lgtm, size/S, updatebot

#5747 chore(deps): bump jenkins-x/jenkins-x-builders from 0.1.564 to 1.2.3
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  jenkins-x-platform/values.yaml
Labels: size/XS, updatebot

#5748 chore(deps): bump jenkins-x/jenkins-x-builders from 1.2.3 to 0.1.564
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  jenkins-x-platform/values.yaml
Labels: size/XS, updatebot

#5752 chore: no double tagging
  Makefile
Labels: approved, lgtm, size/S

#5754 chore: remove one more RELEASE_VERSION
  Makefile
Labels: approved, lgtm, size/XS

#5758 chore: update to newest builders to make updatebot work
  jenkins-x.yml
Labels: approved, size/S

#5726 chore: update to new updatebot for make PR
  .updatebot.yml
  Makefile
Labels: approved, size/XS

#5761 chore: bump builder to prevent double tagging
  jenkins-x.yml
Labels: approved, lgtm, size/S

#5762 chore: Updating OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS
