Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-05, with the labels that each got.

#5375 fix: upgrade the builders version
  jenkins-x-platform/values.yaml
Labels: approved, size/M

#5382 fix: adding static builders for node8 & node10
  jenkins-x-platform/values.yaml
Labels: approved, size/M

#5353 Added Machine Learning builder to platform
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#5391 upgrade jenkins
  jenkins-x-platform/requirements.yaml
Labels: approved, size/XS

#5403 fix: lets let 'jx gc activities' GC old PipelineRun resources
  jenkins-x-platform/values.yaml
Labels: approved, size/XS
