Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-01, with the labels that each got.

#4613 fix: add missing RBAC to list environments
  values.yaml
Labels: approved, size/XS

#4614 fix: add RBAC to list plugins too
  values.yaml
Labels: approved, size/XS

#4652 gcpreviews should run with the jenkins serviceaccount
  values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#4367 fix: Give service account for role controller enough permissions
  templates/committer-role.yaml
  templates/owner-role.yaml
  values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#4620 chore: Add jtnord to the owners file
  OWNERS
Labels: approved, lgtm, size/XS

#4692 fix: use a docker image with jx + helm + kubectl for gc previews
  values.yaml
Labels: approved, lgtm, size/XS

#4719 lets upgrade exposecontroller
  requirements.yaml
Labels: approved, size/XS

#4728 add an extra optional GKE serviceaccount secret
  templates/core-gke-secret.yaml
Labels: approved, size/S

#4586 Added Builder Pod configuration for Maven+Nodejs
  values.yaml
Labels: approved, ok-to-test, size/M

#4740 fix: corrected name of dlang image
  values.yaml
Labels: approved, size/XS

#4753 chore: lets use maven as the container name for all java versions
  values.yaml
Labels: approved, size/XS

#4755 feat(kaniko) added config to create a kaniko secret
  templates/kaniko-secret.yaml
Labels: approved, size/S

#4756 chore: added labels to all generated secret
  templates/docker-cfg-secret.yaml
  templates/gcs-jenkinsx-chartmuseum-secret.yaml
  templates/jx-basic-auth-secret.yaml
  templates/maven-settings-secret.yaml
  templates/npm-token-secret.yaml
  templates/release-gpg-secret.yaml
  templates/ssh-config-secret.yaml
  templates/test-jenkins-user-secret.yaml
Labels: approved, size/S

#4760 fix: upgrade to latest builder images
  values.yaml
Labels: approved, size/M

#4762 Revert "chore: added labels to all generated secret"
  templates/docker-cfg-secret.yaml
  templates/gcs-jenkinsx-chartmuseum-secret.yaml
  templates/jx-basic-auth-secret.yaml
  templates/maven-settings-secret.yaml
  templates/npm-token-secret.yaml
  templates/release-gpg-secret.yaml
  templates/ssh-config-secret.yaml
  templates/test-jenkins-user-secret.yaml
Labels: approved, size/S
