Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-04, with the labels that each got.

#5174 Add patch permission to controllerbuild
  values.yaml
Labels: size/XS

#5173 Fix if-else to keep newline character
  templates/jenkins-x-docker-registry.yaml
Labels: needs-ok-to-test, size/XS

#5199 fix: lets try add a chartmuseum credential
  Makefile
  jenkins-x.yml
Labels: size/XS

#5200 fix: lets try add a chartmuseum credential
  jenkins-x.yml
Labels: size/S

#5201 fix: lets try add a chartmuseum credential
  jenkins-x.yml
Labels: size/XS

#5202 fix: lets try add a chartmuseum credential
  jenkins-x.yml
Labels: size/XS

#5203 fix: add chartmuseum creds
  Makefile
Labels: size/XS

#5204 fix: add user + pass json
  jenkins-x.yml
Labels: size/S

#5206 fix: upgrade container
  jenkins-x.yml
Labels: size/S

#5212 fix: upgrade to new builders
  jenkins-x-platform/values.yaml
Labels: size/M

#5223 bump chartmuseum to get google storage options
  jenkins-x-platform/requirements.yaml
Labels: size/XS

#5249 bump chartmuseum so we get jenkins kubernetes provider annotations
  jenkins-x-platform/requirements.yaml
Labels: approved, size/XS

#5215 fix: container isn't valid, but it isn't needed anyway
  jenkins-x.yml
Labels: approved, size/XS

#5254 fix: upgrade to latest jenkins
  jenkins-x-platform/requirements.yaml
Labels: approved, size/XS

#5258 fix: switch to separate ConfigMaps for each pod template
  Makefile
  jenkins-x-platform/requirements.yaml
  jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
Labels: approved, size/S

#5259 fix: pod template key
  jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
Labels: approved, size/XS

#5261 fix: pod template labels
  jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
Labels: approved, size/XS

#5265 Adding support to mapping Persistent Volume Claim
  jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
Labels: approved, ok-to-test, size/XS

#5267 fix: upgrade to latest builder images
  jenkins-x-platform/values.yaml
Labels: size/M

#5279 fix: add patch roles to all updates roles
  jenkins-x-platform/values.yaml
Labels: approved, size/S

#5297 fix: remove default grafana dashboard stuff
  jenkins-x-platform/values.yaml
Labels: approved, size/XXL

#5298 fix: lets try a helm ignore file
  jenkins-x-platform/.helmignore
Labels: approved, size/XS

#5339 fix: upgrade builder images
  jenkins-x-platform/values.yaml
Labels: approved, size/M
