Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-09, with the labels that each got.

#5930 fix: extend the jx roles with some additional permissions required for jxui-backend to function
  jenkins-x-platform/templates/committer-role.yaml
  jenkins-x-platform/templates/owner-role.yaml
  jenkins-x-platform/templates/viewer-role.yaml
Labels: approved, lgtm, size/XS

#5791 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, size/M

#6076 chore: adding builders for nodejs12x, php5x, and php7x
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, size/L
