Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-02, with the labels that each got.

#4785 fix: for ~/.m2/settings.xml the server.id must align with mirror.id
  values.yaml
Labels: approved, lgtm, size/S

#4815 Added configuration for AWS CDK builder pod
  values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#4816 fix: downgrade to an older jenkins image
  values.yaml
Labels: size/XS

#4818 fix: try an older jenkins image
  values.yaml
Labels: size/XS

#4843 Dummy annotation into kaniko-secret as workaround.
  templates/kaniko-secret.yaml
Labels: approved, ok-to-test, size/XS

#4860 fix: add an automated PR on the jenkins-x-versions repo
  Makefile
Labels: size/XS

#4859 enlarge maven heap memory limit at jenkins-x/jx issue#3098
  values.yaml
Labels: approved, ok-to-test, size/XS

#4864 fix: do not set TILLER_NAMESPACE to an empty string
  templates/jenkins-x-pod-templates.yaml
Labels: approved, ok-to-test, size/XS

#4931 fix: lets disable noisy maven download messages
  values.yaml
Labels: approved, size/XS

#4935 fix: let the build controller view deployments
  values.yaml
Labels: approved, size/XS
