Repository jenkins-x/jenkins-x-platform, pull requests merged in 2019-11, with the labels that each got.

#5396 added terraform logo for the soon to have build-pack
  jenkins-x-platform/images/terraform.png
Labels: size/XS

#5408 Readme update. Fix hyperlinks and Sonatype reference.
  README.md
Labels: size/XS

#5400 Pod template fixes
  jenkins-x-platform/templates/jenkins-x-pod-templates.yaml
Labels: approved, lgtm, ok-to-test, size/L

#5722 chore: Remove pipelinecontroller
  jenkins-x-platform/.helmignore
  jenkins-x-platform/pipelinecontroller/Chart.yaml
  jenkins-x-platform/pipelinecontroller/README.md
  jenkins-x-platform/pipelinecontroller/pipeline.png
  jenkins-x-platform/pipelinecontroller/templates/deployment.yaml
  jenkins-x-platform/pipelinecontroller/templates/serviceaccount.yaml
  jenkins-x-platform/pipelinecontroller/values.yaml
  jenkins-x-platform/templates/controller-team-config.yaml
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, size/M
