Repository jenkins-x/jenkins-x-platform, pull requests merged in 2020-06, with the labels that each got.

#7200 feat: allow the team roles rules to be overridden
  jenkins-x-platform/templates/committer-role.yaml
  jenkins-x-platform/templates/owner-role.yaml
  jenkins-x-platform/templates/viewer-role.yaml
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, size/L

#7225 feat: Maven-java-14 pod template
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#7233 chore: Add builder-maven-graalvm-java11 builder
  jenkins-x-platform/values.yaml
Labels: approved, size/M
