Repository jenkins-x/jenkins-x-platform, pull requests merged in 2020-07, with the labels that each got.

#7249 chore(deps): external dependencies with Kubernetes 1.16 support
  jenkins-x-platform/requirements.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#7255 fix: Upstream chartmuseum can't be upgraded to from our variant
  jenkins-x-platform/requirements.yaml
Labels: size/XS, updatebot

#7281 fix: Use modern tekton paths
  jenkins-x.yml
Labels: approved, size/XS

#7283 fix: update version of jenkins charts version
  jenkins-x-platform/requirements.yaml
Labels: approved, lgtm, size/XS

#7285 fix: Switch to properly mounted secrets
  Makefile
  jenkins-x.yml
Labels: approved, size/S

#7288 chore: disable Jenkins by default
  jenkins-x-platform/values.yaml
Labels: approved, size/XS

#7290 refactor: remove heapster chart
  jenkins-x-platform/requirements.yaml
  jenkins-x-platform/values.yaml
Labels: approved, lgtm, size/XS
